listRec = [ "Whole-Wheat Strawberry Muffins",
"Scarlet Strawberry Sorbet",
"Strawberry Burrata Salad",
"Strawberry-Ginger Lemonade",
"Quinoa Chicken Salad",
"Almond Custard Tart with Strawberries",
"Honey-Vanilla Yogurt Fruit Salad",
"Buttermilk pancakes with glazed strawberries",
"Strawberry Lemon Water",
"Strawberry Pancakes with Cream Cheese Glaze",
"Refreshing Fruit Salad with Mint and Lime",
"Mixed Berry Crisp",
"Frozen fruit eclairs",
"Lemon Cake With Strawberry Sauce",
"Prenatal Strawberry Banana Smoothies",
"Strawberry Banana Protein Smoothie",
"Strawberry Crumb Bars",
"Cold Buster Fruit Leathers recipes",
"Santa Hat Jell-O Shots",
"Patriotic Dessert Recipe",
"Strawberry Upside-Down Cakes",
"Recipe: Yogurt Breakfast Popsicles",
"Low Carb Vanilla Bean Mascarpone & Triple Berry Medley",
"Spinach and Persimmon Salad with Citrus Dressing recipes",
"Summer Greens and Strawberries with Poppy Seed Dressing",
"Cool Strawberry Cream Recipe 4",
"Sugar-Free Strawberry Jam",
"EASY Strawberry Shortcake Recipe",
"Perfect Strawberry Pie Recipe",
"Wild Blueberry Tart",
"Banana-Rama Mocktail",
"Biscuits",
"Strawberry-Topped French Toast Bake",
"Strawberry Bread",
"Strawberry Avocado Spinach Salad with Greek Yogurt recipes",
"Strawberry Galette",
"Small Batch Strawberry Jam recipes",
"5 Star, Skinny Steak Salad with Dreamy Pomegranate-Balsamic Reduction Sauce recipes",
"Blueberry and Strawberry Clafouti recipes",
"Large Brioche Toast with Roasted and Mashed Honey Sweetened Berries",
"Crostata with Strawberry Jam",
"Lightened Up Berry Shortcake",
"Strawberry-Vanilla Chia Seed Jam",
"Strawberry Rhubarb Crumble",
"Miracle Ice Cream",
"Chilled Strawberry-Rhubarb Soup",
"Brown Sugar Sour Cream Ice Cream with Roasted Summer Berries recipes",
"Strawberry-Basil Bourbon Lemonade",
"Strawberry Watermelon Kiwi Popsicles",
"Matcha Green Tea and Yogurt Snack Bowl recipes",
"Pink Velvet (Diabetic)",
"Grilled Strawberry and Cucumber Salad recipes",
"Rhubarb and Strawberry Crisp",
"Perfect Summer Fruit Salad recipes",
"BRAZILIAN FLAIR RHUBARB STRAWBERRY CAIPIRI",
"Strawberry and Black Pepper Ice Cream recipes",
"Crisp Pastry Waffles",
"Petite Banana Split Cakes",
"Strawberry-Banana Fritters",
"Fresh, Sweet Strawberry Ice Cream recipes",
"Simply Delicious Strawberry Sauce recipes",
"Strawberry Sherbet",
"Chocolate Chip Cupcakes with Strawberry Filling + Natushka’s Birthday! recipes",
"Tropical Fruit Celebration Drinks",
"Low-Carb Strawberry Cheesecake",
"Yogurt Slices",
"Red, White and Blue Americana Pops",
"Wings with Berry Balsamic BBQ Sauce",
"Simple cheesecake slice",
"Strawberry Ice Cream Soda",
"Avocado Lime Fruit Salad",
"Flagnarde",
"White-Chocolate-Dipped Strawberries with Citrus Sugar",
"Fancy Pavlova",
"Pistachio Pavlova with Rhubarb Cream",
"Strawberry Papaya and Blood Orange Margaritas",
"Strawberry And Chia Seed Jam",
"Sparkling Fruit Smoothie",
"Fruit Pizza",
"Dad's Summertime Fruit Salad",
"The Lord of the Rings: Samwise Gamgee's Strawberry Pudding",
"Strawberry Quinoa Muffins",
"Strawberry Granita with Whipped Cream",
"Halo Halo",
"Fluffy Butter Cake with Strawberries and W",
"Italian Strawberry Tart",
"strawberry cheesecakes",
"Strawberry Salsa",
"Strawberry Pomegranate Smoothie",
"Strawberry, Burrata and Basil Salad recipes",
"Bug Juice Smoothies",
"Rhubarb-Strawberry Pie",
"Pineapple-Berry Salad with Honey-Mint Dressing",
"Berry Cream Cobbler",
"Very Simple Strawberry Sauce",
"Strawberry Avocado Basil Salsa",
"Overnight Strawberry Cream Cheese Sweet Rolls recipes",
"Strawberry Pecan Short Cake with Vanilla Bean Yogurt",
"Justin's Favorite Pudding with Strawberry Sauce",
"Thermomix Coconut Bread",
"Strawberry-Rhubarb Crumble",
"Fresh Picked Strawberry Muffins recipes",
"Buttermilk Cake Doughnuts with Fresh Strawberry Glaze recipes",
"Cheesecake Filled Strawberries recipes",
"Diner Style Strawberry Pie",
"summertime berry lemonade",
"White Chocolate Strawberry Bread Pudding",
"Strawberry Cream Cheese Bread",
"Feta Bites",
"Old-Fashioned Shortcake",
"Balsamic Marinated Strawberry Trifle",
"Strawberries & cream",
"Strawberry Pretzel Dessert",
"Strawberries and Cream Bread",
"Pineapple Flambé",
"Easy Low Fat Strawberry Triffle Recipe",
"Strawberry Granola Squares",
"Quinoa Salad with Spinach and Berries",
"Berry Cake recipes",
"Strawberry Seed Jam recipes",
"Strawberry Shortcake No Churn Ice Cream recipes",
"Easy Dreamy Strawberry Cream Cake",
"Baby Pb & J Bagel Sandwiches",
"Party Trays!",
"Red White and Blue Ice Cream Pie",
"Rhubarb Butter Cake - Elegant and Simplist",
"Strawberry Shortcake",
"Tres Leches Cake recipes",
"Strawberry-Banana Parfaits",
"Rice Krispy Treats with Fresh Fruit recipes",
"Strawberry Shortcake",
"Warm Chocolate Melting Cups Recipe 4",
"Strawberry Frozen Yogurt Bites - Comeback",
"Strawberry & Cream Sandwich Cake (torta genovese con fragole e panna montata)",
"Berry Lust",
"Banana Split Popsicle for One recipes",
"Mom's Strawberry Squares",
"S'more Peanut Butter Panini",
"Strawberry Lemonade Cupcakes",
"5 Minute Prep + No Churn! recipes" ]

